### PR TITLE
Use subclasses instead of union for PlSlice

### PR DESCRIPTION
**Pull request by kamahen**
This change isn't strictly necessary, but I think it's cleaner and more idiomatic C++.
(It's also slightly less efficient because it creates a unique_ptr which is then deleted; but that's how subclasses need to be returned; and I doubt that the efficiency change will be noticeable.)

The `rocksdb::Slice` class isn't designed for subclassing because it doesn't have a virtual destructor; that's why the new code's `PlSlice` uses encapsulation. `PlSlice` is an semi-abstract base class (it contains a `rocksdb::Slice`, with a subclasses used to provide concrete implementations.

This PR also adds some test cases.

### CODE REVIEW

**Comment by kamahen** [comment]
The 2nd commit removes `using namespace rocksdb` as recommended by https://google.github.io/styleguide/cppguide.html#Namespaces

**Comment by JanWielemaker** [comment]
Hi Peter,

There seem to be two problems.   On my machine I get

```
ERROR: cpp/rocksdb4pl.cpp: In function ‘std::unique_ptr<PlSlice> get_slice(PlTerm, blob_type)’:
ERROR: cpp/rocksdb4pl.cpp:436:47: error: ‘class PlRecordExternalCopy’ has no member named ‘data’
ERROR:   436 |         return std::make_unique<PlSliceStr>(e.data());
ERROR:       |                                               ^~~~
```

On our dev machine the `master` doesn't compile and stops with

```
ERROR: g++: error: unrecognized command line option ‘-Warith-conversion’; did you mean ‘-Wint-conversion’?
```

That is gcc 9.4 on Ubuntu 20.04.   I try to support the oldest supported Linux LTS versions (unless there is a really important reason not to).   In general, do not use specific warning flags.   Only `-Wall`.    If you want more during development, use `CXXFLAGS=... cmake ...`.    That avoids production builds from failing on platforms with different compilers.

**Comment by kamahen** [comment]
I forgot to push a small change to SWI-cpp2.h - https://github.com/SWI-Prolog/packages-cpp/pull/44

I'll remove the warning flags - evidently `-Warith-conversion` isn't in older compilers.

What command(s) do you use for building/testing this?  I think that this pack uses "make" and not "cmake" (because rocksdb uses "make") ...

In general, what's "best practice" for building/testing a pack? Do you go through the whole build+install each time? What command should I use for local build/test and also what command for a final test before pushing (and should I update the version number with each PR?)? Maybe this should be discussed in the Discourse group - or maybe I missed the appropriate section in the documentation ...
I'm currently using this command, which is a bit painful because it runs the rocksdb "make" even though nothing has changed:
`make -C $SRC/rocksdb SUBMODULE_UPDATE= SWIPL=$BUILD_DIR/src/swipl PACKSODIR=/tmp/rocksdb-so SOEXT=so CFLAGS="-fPIC -pthread -I$SRC/swipl-devel/src -I$SRC/swipl-devel/src/os -I$SRC/swipl-devel/packages/cpp -gdwarf-2 -g3" plugin check`

**Comment by JanWielemaker** [comment]
> In general, what's "best practice" for building/testing a pack?

When you start: clone the git repo, go into the repo and run

    ?- pack_install(.).

That builds the pack locally and creates a symlink to make it available.  Now, after editing you have two options.   You can run

    ?- pack_rebuild(rocksdb).

That runs `make clean` and `make` with the right environment.   I though it always writes a file `buildenv.sh` that you can source to get the environment to use normal `make`.     Seems that is only the case there is a `configure` step, i.e., if there is `configure.in` or `configure`.

Note that the current build process also supports cmake.   Might be a good idea to switch to that.   Not sure whether there is an example around.

P.s.  Now compiles.  Thanks.   Merged.   There are still several warnings (g++ 11.3):

```
Warning: In file included from rocksdb/include/rocksdb/options.h:20,
Warning:                  from rocksdb/include/rocksdb/block_cache_trace_writer.h:8,
Warning:                  from rocksdb/include/rocksdb/db.h:20,
Warning:                  from cpp/rocksdb4pl.cpp:38:
Warning: rocksdb/include/rocksdb/advanced_options.h:673:24: warning: conversion to ‘std::vector<int>::size_type’ {aka ‘long unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
Warning:   673 |       std::vector<int>(num_levels, 1);
Warning:       |                        ^~~~~~~~~~
Warning: In file included from rocksdb/include/rocksdb/db.h:26,
Warning:                  from cpp/rocksdb4pl.cpp:38:
Warning: rocksdb/include/rocksdb/sst_file_writer.h: In constructor ‘rocksdb::ExternalSstFileInfo::ExternalSstFileInfo(const string&, const string&, const string&, rocksdb::SequenceNumber, uint64_t, int32_t, int32_t)’:
Warning: rocksdb/include/rocksdb/sst_file_writer.h:58:21: warning: conversion to ‘uint64_t’ {aka ‘long unsigned int’} from ‘int32_t’ {aka ‘int’} may change the sign of the result [-Wsign-conversion]
Warning:    58 |         num_entries(_num_entries),
Warning:       |                     ^~~~~~~~~~~~
Warning: In file included from rocksdb/include/rocksdb/transaction_log.h:13,
Warning:                  from rocksdb/include/rocksdb/db.h:28,
Warning:                  from cpp/rocksdb4pl.cpp:38:
Warning: rocksdb/include/rocksdb/write_batch.h: In member function ‘bool rocksdb::SavePoint::is_cleared() const’:
Warning: rocksdb/include/rocksdb/write_batch.h:61:44: warning: conversion to ‘long unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
Warning:    61 |   bool is_cleared() const { return (size | count | content_flags) == 0; }
Warning:       |                                            ^~~~~

```

**Comment by kamahen** [comment]
I've reported these warnings to the rocksdb team: https://github.com/facebook/rocksdb/issues/11457
They seem to be "harmless", but annoying.

**Pull request merged**
